name = "SpaceLiDAR"
uuid = "29bf0bfc-420f-4fa5-b441-811fd9e6e11d"
authors = ["Maarten Pronk", "Deltares"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
